/* Generated By:JavaCC: Do not edit this line. LexParseConstants.java */

/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface LexParseConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int IDENTIFICADOR = 6;
  /** RegularExpression Id. */
  int LETRA = 7;
  /** RegularExpression Id. */
  int PARTE_LETRA = 8;
  /** RegularExpression Id. */
  int NUM = 9;
  /** RegularExpression Id. */
  int MAS = 10;
  /** RegularExpression Id. */
  int POR = 11;
  /** RegularExpression Id. */
  int PARI = 12;
  /** RegularExpression Id. */
  int PARD = 13;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<IDENTIFICADOR>",
    "<LETRA>",
    "<PARTE_LETRA>",
    "<NUM>",
    "\"+\"",
    "\"*\"",
    "\"(\"",
    "\")\"",
  };

}
